package server;

public enum MsgClient {
    DEFAULT,
    TOAST,
    CONFIRM_REGISTRATION,
    DECLINE_REGISTRATION,
    CONFIRM_PICKUP,
    DECLINE_PICKUP,
    TEAMMATE_PICKUP,
    DECLINE_ACHORN,
    CONFIRM_ACHORN,
    UPDATE_EXCLUDE_LIST
}
