package server;

public enum MsgClient {
    DEFAULT,
    TOAST,
    CONFIRM_REGISTRATION,
    DECLINE_REGISTRATION,
    CONFIRM_PICKUP,
    DECLINE_PICKUP,
    TEAMMATE_PICKUP,
    DECLINE_ACORN,
    CONFIRM_ACORN,
    UPDATE_EXCLUDE_LIST,
    YOU_OWN_THIS_ACORN
}
